version: '3.8'

services:
  frontend:
    image: node:14
    working_dir: /app/frontend
    volumes:
      - ./frontend:/app/frontend
    command: bash -c "npm install && npm start"
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    image: node:14
    working_dir: /app/backend
    volumes:
      - ./backend:/app/backend
    command: bash -c "npm install && npm start"
    ports:
      - "5000:5000"
    environment:
      - PORT=5000